easy_admin:
    site_name: '%env(SITE_NAME)%'
    design:
            brand_color: '#1ABC9C'
    entities:
        Product:

          # List the entity class name you want to manage
          class: App\Entity\Product
