easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin/{_locale}
    type: annotation
    defaults:
        _locale: zh_CN
    requirements:
        _locale:  zh_CN|en
